config/routes.rb
Rails.application.routes.draw do

  root to: "breweries#index"

  resources :users, only: [:new, :create, :show]

  resources :breweries, only: [:index, :show]

  resources :beers, only: [:index, :show] do
    resources :ratings, only: [:create, :update]
  end

  resources :styles, only: [:index, :show]

  namespace :admin do
    resources :breweries
    resources :beers
    resources :styles
  end

  post '/breweries', to: 'admin/breweries#create'
  patch '/breweries/:id', to: 'admin/breweries#update'

  post '/styles', to: 'admin/styles#create'
  patch '/styles/:id', to: 'admin/styles#update'

  post '/beers', to: 'admin/beers#create'
  patch '/beers/:id', to: 'admin/beers#update'


  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/beer.rb
class Beer < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :brewery_id, presence: true
  validates :style, presence: true

  belongs_to :brewery
  belongs_to :style

  has_many :ratings
  has_many :users, through: :ratings
end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :location, presence: true

  has_many :beers
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  validates :user_id, presence: true
  validates :beer_id, presence: true
  validates :value, presence: true
  validates_inclusion_of :value, :in => 1..5

  belongs_to :user
  belongs_to :beer
end

app/models/style.rb
class Style < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :beers
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true

  enum role: ["default", "admin"]

  has_many :ratings
  has_many :beers, through: :ratings
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  before_action :require_admin

  def require_admin
    render file: '/public/404' unless current_admin?
  end

end

app/controllers/admin/beers_controller.rb
class Admin::BeersController < Admin::BaseController

  before_action :set_beer, only: [:show, :edit, :update, :destroy]

  def index
    @beers = Beer.all
  end

  def new
    @beer = Beer.new
    @breweries = Brewery.all
    @styles = Style.all
  end

  def create
    @beer = Beer.new(beer_params)
    @breweries = Brewery.all
    @styles = Style.all

    if @beer.save
      redirect_to beer_path(@beer)
    else
      render :new
    end
  end

  def show
  end

  def edit
    @breweries = Brewery.all
    @styles = Style.all
  end

  def update
    if @beer.update(beer_params)
      redirect_to admin_beer_path(@beer)
    else
      render :edit
    end
  end

  def destroy
    @beer.destroy
    redirect_to admin_beers_path
  end

private

  def set_beer
    @beer = Beer.find(params[:id])
  end

  def beer_params
    params.require(:beer).permit(:name, :brewery_id, :style_id)
  end

end

app/controllers/admin/breweries_controller.rb
class Admin::BreweriesController < Admin::BaseController

  before_action :set_brewery, only: [:show, :edit, :update, :destroy]

  def index
    @breweries = Brewery.all
  end

  def new
    @brewery = Brewery.new
  end

  def create
    @brewery = Brewery.new(brewery_params)

    if @brewery.save
      redirect_to brewery_path(@brewery)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @brewery.update(brewery_params)
      redirect_to admin_brewery_path(@brewery)
    else
      render :edit
    end
  end

  def destroy
    @brewery.destroy
    redirect_to admin_breweries_path
  end

private

  def set_brewery
    @brewery = Brewery.find(params[:id])
  end

  def brewery_params
    params.require(:brewery).permit(:name, :location)
  end

end

app/controllers/admin/styles_controller.rb
class Admin::StylesController < Admin::BaseController

  before_action :set_style, only: [:show, :edit, :update, :destroy]

  def index
    @styles = Style.all
  end

  def new
    @style = Style.new
  end

  def create
    @style = Style.new(style_params)

    if @style.save
      redirect_to style_path(@style)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @style.update(style_params)
      redirect_to admin_style_path(@style)
    else
      render :edit
    end
  end

  def destroy
    @style.destroy
    redirect_to admin_styles_path
  end

private

  def set_style
    @style = Style.find(params[:id])
  end

  def style_params
    params.require(:style).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end

end

app/controllers/beers_controller.rb
class BeersController < ApplicationController

  def index
    @beers = Beer.all
  end

  def show
    @beer = Beer.find(params[:id])
    @rating = Rating.new
  end

private

  def beer_params
    params.require(:beer).permit(:name, :brewery, :style)
  end

end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController

  def index
    @breweries = Brewery.all
  end

  def show
    @brewery = Brewery.find(params[:id])
  end

private

  def brewery_params
    params.require(:brewery).permit(:name, :location)
  end

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_beer, only: [:create, :update]

  def create
    @rating = @beer.ratings.new(value: params[:rating][:value], user_id: current_user.id)

    # @rating.beer = Beer.find(params[:beer_id])
    # @rating.user = current_user
    if @rating.save
      flash[:success] = "Thanks for your input! Your rating has been stored!"
      redirect_to beer_path(params[:beer_id])
    else
      flash[:failure] = "Please select a rating before hitting submit"
    end
  end

  def update
    @rating = Rating.find(params[:id])
    @rating.update_attribute :value, params[:value]
  end

private

  def set_beer
    @beer = Beer.find(params[:beer_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash.now[:error] = "Invalid. Try Again."
      render :new
    end
  end

  def destroy
    session.clear
    flash[:notice] = "Goodbye!"
    redirect_to login_path
  end
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController

  def index
    @styles = Style.all
  end

  def show
    @style = Style.find(params[:id])
  end


private

  def style_params
    params.require(:style).permit(:name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash.now[:error] = @user.errors.full_messages.join(", ")
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/beers/edit.html.erb
<h1>Edit Beer</h1>

<%= form_for(@beer) do |f| %>
  <% if @beer.errors.any? %>
    <h2><%= pluralize(@beer.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% @beer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :brewery %>
  <%= f.collection_select(:brewery_id, @breweries, :id, :name, { include_blank: 'Select a brewery'}, { class: 'brewery-select'}) %>

  <%= f.label :style %>
  <%= f.collection_select(:style_id, @styles, :id, :name, { include_blank: 'Select a style'}, { class: 'style-select' }) %>

  <%= f.submit %>
<% end %>

app/views/admin/beers/index.html.erb
<h1>Beers Index - Admin</h1>
<table class="table table-striped table-bordered">
  <% @beers.each do |beer| %>
    <tr>
      <td><%= link_to beer.name, admin_beer_path(beer) %></td>
      <td><%= beer.brewery.name %></td>
      <td><%= beer.style.name %></td>
    </tr>
<% end %>
</table>

app/views/admin/beers/new.html.erb
<h1>New Beer</h1>

<%= form_for(@beer) do |f| %>
  <% if @beer.errors.any? %>
    <h2><%= pluralize(@beer.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% @beer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :brewery %>
  <%= f.collection_select(:brewery_id, @breweries, :id, :name, { include_blank: 'Select a brewery'}, { class: 'brewery-select'}) %>

  <%= f.label :style %>
  <%= f.collection_select(:style_id, @styles, :id, :name, { include_blank: 'Select a style'}, { class: 'style-select' }) %>

  <%= f.submit %>
<% end %>

app/views/admin/beers/show.html.erb
<h1><%= @beer.name %> - Admin</h1>
<h2><%= @beer.brewery.name %></h2>
<h2><%= @beer.style.name %></h2>

<footer>
  <%= link_to "Delete Beer", admin_beer_path(@beer), method: :delete %>
  <%= link_to "Edit Beer", edit_admin_beer_path(@beer) %>
</footer>

app/views/admin/breweries/edit.html.erb
<h1>Edit Brewery</h1>

<%= form_for(@brewery) do |f| %>
  <% if @brewery.errors.any? %>
    <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% @brewery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.submit %>
<% end %>

app/views/admin/breweries/index.html.erb
<h1>Breweries Index - Admin</h1>
<table class="table table-striped table-bordered">
  <% @breweries.each do |brewery| %>
    <tr>
      <td><%= link_to brewery.name, admin_brewery_path(brewery) %></td>
      <td><%= brewery.location %></td>
    </tr>
<% end %>
</table>

app/views/admin/breweries/new.html.erb
<h1>New Brewery</h1>

<%= form_for(@brewery) do |f| %>
  <% if @brewery.errors.any? %>
    <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% @brewery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.submit %>
<% end %>

app/views/admin/breweries/show.html.erb
<h1><%= @brewery.name %> - Admin</h1>
<h2><%= @brewery.location %></h2>

<footer>
  <%= link_to "Delete Brewery", admin_brewery_path(@brewery), method: :delete %>
  <%= link_to "Edit Brewery", edit_admin_brewery_path(@brewery) %>
</footer>

app/views/admin/styles/edit.html.erb
<h1>Edit Style</h1>

<%= form_for(@style) do |f| %>
  <% if @style.errors.any? %>
    <h2><%= pluralize(@style.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% @style.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/admin/styles/index.html.erb
<h1>Styles Index - Admin</h1>
<table class="table table-striped table-bordered">
  <% @styles.each do |style| %>
    <tr>
      <td><%= link_to style.name, admin_style_path(style) %></td>
    </tr>
<% end %>
</table>

app/views/admin/styles/new.html.erb
<h1>New Style</h1>


<%= form_for(@style) do |f| %>
  <% if @style.errors.any? %>
    <h2><%= pluralize(@style.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% @style.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/admin/styles/show.html.erb
<h1><%= @style.name %> - Admin</h1>

<footer>
  <%= link_to "Delete Style", admin_style_path(@style), method: :delete %>
  <%= link_to "Edit Style", edit_admin_style_path(@style) %>
</footer>

app/views/beers/index.html.erb
<h1>Beers Index</h1>
<table class="table table-striped table-bordered">
  <% @beers.each do |beer| %>
    <tr>
      <td><%= link_to beer.name, beer_path(beer) %></td>
      <td><%= beer.brewery.name %></td>
      <td><%= beer.style.name %></td>
    </tr>
<% end %>
</table>

app/views/beers/show.html.erb
<h1><%= @beer.name %></h1>
<h2><%= link_to @beer.brewery.name, brewery_path(@beer.brewery) %> - <%= @beer.brewery.location %></h2>
<h2><%= link_to @beer.style.name, style_path(@beer.style) %></h2>


<%= simple_form_for [@beer, @rating], url: beer_ratings_path(@beer), method: :post do |f| %>
  <%= f.input :value, :label => "Rating", :collection => 1..5, :as => :radio_buttons %>
  <%= f.button :submit, "Rate this beer!" %>
<% end %>

app/views/breweries/index.html.erb
<h1>Breweries Index</h1>
<table class="table table-striped table-bordered">
  <% @breweries.each do |brewery| %>
    <tr>
      <td><%= link_to brewery.name, brewery_path(brewery) %></td>
      <td><%= brewery.location %></td>
    </tr>
<% end %>
</table>

app/views/breweries/show.html.erb
<h1><%= @brewery.name %></h1>
<h2><%= @brewery.location %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Whats Brewin</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <% if current_user %>
    Welcome, <%= current_user.username %>
      <%= link_to "Logout", logout_path, method: :delete %>
    <% else %>
      <%= link_to "Login", login_path %>
    <% end %>
  </div>

  <% flash.each do |name, message| %>
    <%= content_tag :div, message, id: "flash_#{name}" %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/styles/index.html.erb
<h1>Styles Index</h1>
<table class="table table-striped table-bordered">
  <% @styles.each do |style| %>
    <tr>
      <td><%= link_to style.name, style_path(style) %></td>
    </tr>
<% end %>
</table>

app/views/styles/show.html.erb
<h1><%= @style.name %></h1>

app/views/users/new.html.erb
<h2>So you fancy yourself a beer connoisseur, ay? Well then we are happy to have you! Sign up below!</h2>

<%= form_for(@user) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit "Create Account" %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome, <%= current_user.username %>!</h1>